🎉 Added histology-to-cBio data sheet script
PediatricOpenTargets/OpenPBTA-analysis pull request #180
Opened 2022-05-23 19:59 UTC by migbro

:pencil: Updated readme with info from this addition

### Purpose/implementation Section

#### What scientific question is your analysis addressing?

Could a histologies file be shoe-horned into cBioportal data sheets format?

#### What was your approach?

Brute force

#### What GitHub issue does your pull request address?

https://github.com/PediatricOpenTargets/ticket-tracker/issues/296

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

Please let me know if items in the checklist below are relevant to this addition.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

### Results

#### What types of results are included (e.g., table, figure)?

NA - can be created upon request

#### What is your summary of the results?

They load - but two poly A technical replicates have to be removed ahead of time.

#### Reproducibility Checklist

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2022-06-01 01:03 UTC, jharenza requested changes
Hi @migbro! Thanks for adding this, but can you format it such that the `pedcbio-sample-name` module contains a bash script to run all scripts within this module and the script runs in the docker container?

Ideally, what we want to see here is a module setup similar to other modules. 

We might rename this module something like `pedcbio-histologies-prep`, rename [run_add_name.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/pedcbio-sample-name/run_add_name.sh) to `run-pedcbio-histologies-prep.sh`, and within the shell script, run the R code and your python code. We would rename [pedcbio_sample_name_col.R](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/pedcbio-sample-name/pedcbio_sample_name_col.R) as `01-pedcbio_sample_name_col.R` to be run first, then rename [clinical_to_datasheets.py](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/180/files#diff-ad55213bbd41e3f51be32d3345fee5bf09560a3f7dc9766101888c55915ee03d) to `02-clinical_to_datasheets.py` and place these in order within the shell script.

For `02-clinical_to_datasheets.py`, we would normally want to pull in the `histologies.tsv` from `/data`, but since `pedcbio_sample_name_col.R` is creating [histologies-formatted-id-added.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/pedcbio-sample-name/results/histologies-formatted-id-added.tsv) which you use as input, you would call this file and your code would reformat based on it.

Finally, while you mention that the results will be pushed to S3, we would also want that final pedcbio clinical file to output into the `/results` folder here.

Will you please make the above modifications?

2022-06-01 01:03 UTC, jharenza commented on analyses/pedcbio-sample-name/README.md
> +Outputs a `data_clinical_sample.txt` and `data_clinical_patient.txt` for the cBio package, and a `bs_id_sample_map.txt` mapping file to link BS IDs to generated cBioPortal IDs based on the rules for
Note: starting with the next version (11), we will no longer have `parent_aliquot_id`. Do you need this field specifically? If so, we should have @nicholasvk bring it back into the data warehouse view.

2022-06-01 13:21 UTC, migbro commented on analyses/pedcbio-sample-name/README.md
> +Outputs a `data_clinical_sample.txt` and `data_clinical_patient.txt` for the cBio package, and a `bs_id_sample_map.txt` mapping file to link BS IDs to generated cBioPortal IDs based on the rules for
Hmmm, I might have to review this, because we might not. The cBio names that used this were for CBTN - as long that doesn't go away from where I pull it now (`prod.specimens` I think?) should be ok. Said another way, since sample naming is either handled for PBTA and KF in data warehouse via dbt, and the rest through rules set in Run's script in the histologies file, this script doesn't have to do sample naming anymore.

2022-10-24 20:17 UTC, migbro commented
Can we make the bash script requirement a different ticket? the code itself works and I lost a bit of time realizing that my fixes to this weren't in dev branch yet while trying to reprocess the study

2022-10-26 20:04 UTC, jharenza commented
I am going to close this - if we decide to update this in the future, we can create a new PR

2022-10-26 20:04 UTC, closed without merging

2022-10-26 20:21 UTC, migbro commented
Gah! I need the code merged though because as-is it doesn't work. Even without the bash script, the cbio naming part works with this PR, and that's the most important part in conjunction with follwing the readme on the pedcbio etl