Update build-and-push-docker.yml
PediatricOpenTargets/OpenPBTA-analysis pull request #22
Opened 2021-06-15 17:59 UTC by kgaonkar6

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Updating dockerhub account to d3b-bixu/open-pedcan

#### What was your approach?
Yuankun created a repo on SBG docker registry which we will update as the docker image repository in the workflow.
d3b-bixu/open-pedcan

#### What GitHub issue does your pull request address?

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

### Results

#### What types of results are included (e.g., table, figure)?

#### What is your summary of the results?

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2021-06-22 17:56 UTC, jharenza commented
hi @dmiller15 - following up on the review for this - when do you think you can review?

2021-07-01 20:22 UTC, dmiller15 requested changes

2021-07-01 20:22 UTC, dmiller15 commented on .github/workflows/build-and-push-docker.yml
> +          tags: pgc-images.sbgenomics.com/d3b-bixu/open-pedcan:latest
I don't think `pgc-images.sbgenomics.com/` will work here. Tags should be `<username>/<appname>:<version>`

2021-07-01 20:42 UTC, dmiller15 approved these changes
I'd say just go for it and adjust if it doesn't work.

2021-07-02 00:22 UTC, merged