Immune deconv quantiseq
PediatricOpenTargets/OpenPBTA-analysis pull request #224
Opened 2022-07-18 15:25 UTC by kelseykeith

### Purpose/implementation Section

#### What scientific question is your analysis addressing?

Update the `immune-deconv` module to add quanTIseq and remove CIBERSORT as deconvolution options in order to to stay up to date with OpenPBTA <https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv>

#### What was your approach?

Made minimal changes to add `quanTIseq` as an option and to remove `CIBERSORT` as an option when running `immunedeconv`. Code is not completely identical to the OpenPBTA module since we run the deconvolution by cancer type.

#### What GitHub issue does your pull request address?

Updated analysis: immune-deconv to include quanTIseq #321 <https://github.com/PediatricOpenTargets/ticket-tracker/issues/321>

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

1. Review the code
2. Test run the module with both the xcell and quanTIseq options. XCell results should be unchanged from previous since no changes were made there. 
3. Check both outputs for consistency.

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

### Results

#### What types of results are included (e.g., table, figure)?

RDS files and PDF plots

#### What is your summary of the results?

- `results/quantiseq_output.rds`
- `results/xcell_output.rds`
- `plots/quantiseq_heatmap_by_group.pdf`
- `plots/xcell_heatmap_by_group.pdf`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

2022-08-05 13:38 UTC, aadamk commented on analyses/immune-deconv/README.md
> +For `xCell`, the results in the rds file are predicted immune scores per cell type per input sample. These scores are not actual cell fractions but arbitrary scores representing enrichment of the cel
```suggestion
For `xCell`, the results in the rds file are predicted immune scores per cell type per input sample. These scores are not actual cell fractions but arbitrary scores representing enrichment of the cell types which can be compared across various cancer/gtex groups. The `quanTIseq` results, in contrast, provide an absolute score that can be interpreted as a cell fraction and the results in the rds file are the absolute scores per cell type per input sample. Depending on the user requirements, the output can also be used to create various visualizations. 
```

2022-08-05 13:38 UTC, aadamk commented on analyses/immune-deconv/01-immune-deconv.R
> +# Author: Komal S. Rathim updated, 2020-07 Kelsey Keith
```suggestion
# Author: Komal S. Rathi updated, 2020-07 Kelsey Keith
```

2022-08-08 18:31 UTC, aadamk approved these changes
thank you for this PR @kelseykeith 
i completed end-to-end testing and this module ran successfully for me. 
just a couple of typos to resolve before merging.

2022-08-09 13:01 UTC, jharenza commented
Thanks for the review @aadamk , and work on this @kelseykeith! I would like to hold on the merge until we finalize GitHub actions testing data so this can also run through GA. I should be able to wrap this up in the next two days.

2022-08-10 20:13 UTC, jharenza commented
@kelseykeith to move this one forward for our toolkit purposes, I merged dev and uncommented immune deconv in the YAML file. 🤞

2022-08-11 12:34 UTC, kelseykeith commented
Great, I will try rerunning!

2022-08-11 12:43 UTC, jharenza commented
You don't actually have to do anything else right now- I just wanted it to trigger a GitHub actions run. It failed, but not because of your module, because MRAN is down and the docker image could not build. We can restart the job and see how it goes, so we will wait on the GA for anything further!

2022-08-11 12:44 UTC, kelseykeith commented
Ok, great, never mind then!

2022-08-11 18:53 UTC, jharenza commented
@kelseykeith can you fix the merge conflicts with the analysis readme please?

2022-08-11 19:12 UTC, kelseykeith commented
Done!

2022-08-12 00:48 UTC, jharenza requested changes
see comments about updating to use the data dir instead of a specific version

2022-08-12 00:48 UTC, jharenza commented on analyses/immune-deconv/run-immune-deconv.sh
> +--clin_file '../../data/v11/histologies.tsv' \
please set these to use the data folder directly - I think this is why the module is failing

2022-08-12 00:48 UTC, jharenza commented on analyses/immune-deconv/run-immune-deconv.sh
> +--clin_file '../../data/v11/histologies.tsv' \
same comment - use the data dir

2022-08-12 13:36 UTC, kelseykeith commented
Done! Sorry I forgot to change them back

2022-08-12 18:10 UTC, jharenza approved these changes
perfect, thank you!

2022-08-12 18:10 UTC, merged