Generate pre-release analysis files
PediatricOpenTargets/OpenPBTA-analysis pull request #250
Opened 2022-09-02 19:27 UTC by ewafula

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
bash script to generate pre-lease analysis files 

#### What was your approach?
Bash script to run pre-release analysis modules described in the ticket and upload to the s3 bucket

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/402

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
Review the entire bash script code and look through pre-release data files upload on the s3 bucket:
- https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/analysis-files-pre-release
- https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/analysis-files-pre-release-commit

#### Is there anything that you want to discuss further?
Additional analyses modules were updated that were not running properly
- independent-samples module (minor edit, failing load base histologies files)
- tp53_nf1_score (several script amended)

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results

#### What types of results are included (e.g., table, figure)?
Tables 

#### What is your summary of the results?
- https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/analysis-files-pre-release
- https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/analysis-files-pre-release-commit

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

2022-09-06 20:58 UTC, jharenza commented
@zhangb1 and @yuankunzhu can you review this as a script which can be run in one swoop on EC2 to generate all release data files post initial matrix generation (eg, SNV consensus MAF + fusion, CNV files from each algorithm)? Thanks

2022-09-13 14:58 UTC, zhangb1 approved these changes

2022-09-13 18:14 UTC, jharenza requested changes
Thanks for putting this together. I had a few suggestions of files to keep for QC checks and then think this PR should also delete `[generate-analysis-files-repo.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/generate-analysis-files-repo.sh)` and [generate-analysis-files-toolkit.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/generate-analysis-files-toolkit.sh) and update [run-for-subtyping.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/run-for-subtyping.sh) to remove the modules now being run upstream.

2022-09-13 18:14 UTC, jharenza commented on analyses/tp53_nf1_score/00-tp53-nf1-alterations.R
> +histology$RNA_library[histology$Kids_First_Biospecimen_ID == "BS_ETC8R0TD"] <- "stranded"
I created [this](https://github.com/PediatricOpenTargets/ticket-tracker/issues/408) ticket to track

2022-09-13 18:14 UTC, jharenza commented on scripts/generate-analysis-files.sh
> +cp ${analyses_dir}/gene-set-enrichment-analysis/results/gsva_scores.tsv ${release_dir}
I think this should go in the commit directory?

2022-09-13 18:14 UTC, jharenza commented on scripts/generate-analysis-files.sh
> +cp ${analyses_dir}/fusion-summary/results/* ${release_dir}
Can you also add these to the commit directory?

2022-09-13 18:14 UTC, jharenza commented on scripts/generate-analysis-files.sh
> +  cp ${analyses_dir}/focal-cn-file-preparation/results/cnvkit_with_status.tsv ${release_dir}
Can you also add these to the commit directory?

2022-09-13 18:14 UTC, jharenza commented on scripts/generate-analysis-files.sh
> +cp ${analyses_dir}/fusion_filtering/results/fusion-putative-oncogenic.tsv ${release_dir}
Can you also add these to the commit directory?

2022-09-21 00:37 UTC, ewafula commented on analyses/tp53_nf1_score/00-tp53-nf1-alterations.R
> +histology$RNA_library[histology$Kids_First_Biospecimen_ID == "BS_ETC8R0TD"] <- "stranded"
Thanks!

2022-09-21 01:12 UTC, ewafula commented
@jharenza, I have made the changes you suggested and included all the subtyping modules that were in the `scripts/run-for-subtyping.sh` script.  I have detected `scripts/generate-analysis-files-toolkit.sh`,  `scripts/generate-analysis-files-toolkit.sh` and `scripts/run-for-subtyping.sh` scripts.  Results for all subtyping modules are only copied to the s3  bucket `pre-release-commit` folder. 

With this PR commit, I have commented out commands to upload files to the s3 bucket `pre-release` and `pre-release-commit` folders for you to check first and confirm that files are being copied to the correct folder.  Once you approve the PR,  I'll rerun the script to upload subtyping files to the `pre-release-commit`  folder.  

I don't have delete permissions on the s3 bucket. Please delete the current content of the `analysis-files-pre-release`  folder as it contains the `tp53` and `gsea` subtyping files that I had previously uploaded with the initial  PR commit. After PR has been fully approved, I will re-upload the pre-release files with a rerun of the script.

2022-09-26 18:57 UTC, jharenza commented
Hi @ewafula can you do a clean rerun of the TP53 module in this branch? I am noticing multiple scores for the same BS_ID. EG:

<img width="737" alt="Screen Shot 2022-09-26 at 2 55 27 PM" src="https://user-images.githubusercontent.com/207034/192357803-8d9fa788-a9e0-4aed-8302-5c249a421f44.png">

2022-09-26 20:31 UTC, ewafula commented
> Hi @ewafula can you do a clean rerun of the TP53 module in this branch? I am noticing multiple scores for the same BS_ID. EG:
> 
> <img alt="Screen Shot 2022-09-26 at 2 55 27 PM" width="737" src="https://user-images.githubusercontent.com/207034/192357803-8d9fa788-a9e0-4aed-8302-5c249a421f44.png">

@jharenza,  duplicates BS_ids are a result of the following code snippet: 
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/65c8be222c98162099fb1446c2dc9b7ceccb9ff1/analyses/tp53_nf1_score/02-qc-rna_expression_score.Rmd#L41-L62

Here the match pattern reads classifier results (`pattern="*classifier_scores.tsv"`), including all of the following:
```
gene-expression-rsem-tpm-collapsed_classifier_scores.tsv
gene-expression-rsem-tpm-collapsed-exome_capture_classifier_scores.tsv
gene-expression-rsem-tpm-collapsed-poly-A_classifier_scores.tsv
gene-expression-rsem-tpm-collapsed-poly-A-stranded_classifier_scores.tsv
gene-expression-rsem-tpm-collapsed-stranded_classifier_scores.tsv
```

I think we need to exclude `gene-expression-rsem-tpm-collapsed_classifier_scores.tsv`,  a remnant result file from older runs that has never been removed and is the cause of duplicate BS_ids.  I'll delete the file and rerun the script.

2022-09-26 20:41 UTC, jharenza commented
great, thank you!

2022-09-26 20:46 UTC, jharenza commented
>I don't have delete permissions on the s3 bucket. Please delete the current content of the analysis-files-pre-release folder as it contains the tp53 and gsea subtyping files that I had previously uploaded with the initial PR commit. After PR has been fully approved, I will re-upload the pre-release files with a rerun of the script.

done

2022-09-26 20:48 UTC, jharenza commented on scripts/generate-analysis-files.sh
> +cp ${analyses_dir}/tp53_nf1_score/results/*.tsv ${commit_dir}
Let's also add the ROC plots

2022-09-26 20:50 UTC, jharenza approved these changes
I will pre-approve now and just double check the TP53 results and commit directory once rerun!

2022-09-26 21:00 UTC, ewafula commented on scripts/generate-analysis-files.sh
> +cp ${analyses_dir}/tp53_nf1_score/results/*.tsv ${commit_dir}
> Let's also add the ROC plots

Ok, will include plots.

2022-09-27 03:39 UTC, ewafula commented
@jharenza regenerated the results but have `Access Denied` to upload to the s3 bucket. I will reach out to Chris to reset permission again.   Chris has been testing permissions when this happens. 

I already updated the PR with the bash script without results for each module run. There are too many files to

2022-09-27 11:50 UTC, ewafula commented
@jharenza, I ran the bash script with the `RUN_LOCAL=1` variable to exclude the large files produced by the `run-gistic` and `focal-cn-file-preparation` modules. Results for all other modules included in the script are uploaded to GitHub with the PR update. I'll wait for Chris to resolve permission issues with my access to the s3 bucket to upload all the files to their respective folders.

2022-09-27 15:28 UTC, ewafula commented
@jharenza, Chris to resolve permission issues. Files are now uploaded to the s3 bucket.

2022-09-28 18:38 UTC, jharenza commented
@ewafula thank you for working on this - I think it looks good. My only remaining comment is maybe we can only retain the `*definining_lesions` and `*molecular_subtype` files for the subtyping modules, rather than each individual lesion file, but we can update that later as needed. May discuss this also with @sickler-alex and @aadamk - maybe once we have the toolkit developed, we can have these outputs committed as well.

2022-09-28 18:40 UTC, merged