V12 cnv freq
PediatricOpenTargets/OpenPBTA-analysis pull request #345
Opened 2023-03-23 02:16 UTC by zzgeng

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Update cnv-frequencies and fusion-frequencies modules with v12 data and change the output column for `somatic_mutation` to `pediatric_cancer`

#### What was your approach?
Change `datatypeId` column value for the output table from `somatic_mutation` to `pediatric_cancer`

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/527
https://github.com/PediatricOpenTargets/ticket-tracker/issues/528

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results

#### What types of results are included (e.g., table, figure)?

#### What is your summary of the results?

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

2023-03-24 19:04 UTC, kelseykeith requested changes
Overall this looks great!

- Except for the PMTL column in the `cnv-frequencies` table (see Issues below), the structure of the new v12 tables for both modules match the v11 version.
- The data mostly match except for adjustments made with the new release.
- The `fusion-frequencies` module has been updated to use the DGD fusions in the `data/` directory, not the file inside the module
- The `datatypeId` column was correctly updated in both modules.

Minor Issues:
  - @ewafula, the PMTL annotation is being removed in v12 correct? So it's right that it's missing from the `cnv-frequencies` table when it was present in v11.
  - I suggested removing the `.gitignore` in the `fusion-frequencies` module since the files are all under 10Mb, well under GitHub's file size limit of 100Mb, but if we're moving away from this model it can be left alone

2023-03-24 19:04 UTC, kelseykeith commented on analyses/fusion-frequencies/results/.gitignore
I would suggest removing this `.gitignore` and pushing the results to GitHub. The `fusion-frequencies` files are small (< 10Mb) and well under GitHub's file size limit so we should be totally fine to continue hosting results here

2023-03-24 19:12 UTC, zzgeng commented on analyses/fusion-frequencies/results/.gitignore
Thank you for your suggestion! I will update the `fusion-frequencies` results.

2023-03-25 19:10 UTC, ewafula commented
> Overall this looks great!
> 
> * Except for the PMTL column in the `cnv-frequencies` table (see Issues below), the structure of the new v12 tables for both modules match the v11 version.
> * The data mostly match except for adjustments made with the new release.
> * The `fusion-frequencies` module has been updated to use the DGD fusions in the `data/` directory, not the file inside the module
> * The `datatypeId` column was correctly updated in both modules.
> 
> Minor Issues:
> 
> * @ewafula, the PMTL annotation is being removed in v12 correct? So it's right that it's missing from the `cnv-frequencies` table when it was present in v11.
> * I suggested removing the `.gitignore` in the `fusion-frequencies` module since the files are all under 10Mb, well under GitHub's file size limit of 100Mb, but if we're moving away from this model it can be left alone

@kelseykeith,  that is correct PMTL is no longer in all MTP tables.

2023-03-25 19:15 UTC, ewafula approved these changes

2023-03-27 12:04 UTC, kelseykeith approved these changes

2023-03-27 12:05 UTC, kelseykeith commented
Thanks for the changes @zzgeng! This looks good now, approved

2023-04-28 18:13 UTC, merged