v12 release notes
PediatricOpenTargets/OpenPBTA-analysis pull request #352
Opened 2023-04-13 20:09 UTC by kelseykeith

### Purpose/implementation Section

#### What scientific question is your analysis addressing?

Updated the release notes for v12

#### What was your approach?

Added changes for v12, particularly additional files and the update to GENCODE v39

#### What GitHub issue does your pull request address?

[Ticket 463](https://github.com/PediatricOpenTargets/ticket-tracker/issues/463)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

Release notes were primarily written using the tickets linked in v12 release ticket [Ticket 431](https://github.com/PediatricOpenTargets/ticket-tracker/issues/431), however, there were some tickets that were not marked as complete or that were marked as v12 that I thought were no longer included. Since it's easier to delete than to go and add those tickets in later, I included everything, but please particularly look at the following tickets to make sure they should be included:

- tickets not marked closed or merged
  - Update gliomatosis cerebri term in LGAT subtyping [Ticket 358](https://github.com/PediatricOpenTargets/ticket-tracker/issues/358)
  - Update EPN analysis to pull new gene names using GENCODE v39 symbols [Ticket 485](https://github.com/PediatricOpenTargets/ticket-tracker/issues/485)
  - Fusion summary to use new gene symbols from GENCODE v39 [Ticket 486](https://github.com/PediatricOpenTargets/ticket-tracker/issues/486)
  - HGG subtyping to include GENCODE v39 gene symbols [Ticket 487](https://github.com/PediatricOpenTargets/ticket-tracker/issues/487)
  - LGG subtyping to take in new H3 gene symbols for GENCODE v39 update [Ticket 488](https://github.com/PediatricOpenTargets/ticket-tracker/issues/488)
  - Incorrect subtypes [Ticket 489](https://github.com/PediatricOpenTargets/ticket-tracker/issues/489)
- tickets apparently relating to PPTC PDX samples
  - Bix Dev PedcbioPortal Support: Update PPTC study reference [Ticket 375](https://github.com/PediatricOpenTargets/ticket-tracker/issues/375) 
  - Create PPTC PDX study base histologies file [Ticket 479](https://github.com/PediatricOpenTargets/ticket-tracker/issues/479)

#### Is there anything that you want to discuss further?

No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

### Results

#### What types of results are included (e.g., table, figure)?

`doc/release-notes.md`

#### What is your summary of the results?

List of changes with tickets referenced for the v12 release

2023-04-13 20:11 UTC, kelseykeith commented
One other note, will need to update the date of the release and the release PR before cutting the v12 release

2023-04-26 23:14 UTC, jharenza requested changes
Thanks so much for starting this- few change requests, but should be good to go soon!

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +    - Reprocess DGD panel data [Ticket 429](https://github.com/PediatricOpenTargets/ticket-tracker/issues/429)
@kelseykeith can you instead remove this and add somewhere, maybe after line 17, that this release removes DGD DNA Panel and then refer to some of those tickets as ongoing.

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +- overview of changes (See [PR XXX](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/) for additional details):
What PR is this supposed to be referring to? Did you mean https://github.com/PediatricOpenTargets/ticket-tracker/issues/431

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +    - Creat merged rMATs matrix for v12 release [Ticket 480](https://github.com/PediatricOpenTargets/ticket-tracker/issues/480)
```suggestion
```

removed this for now

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +    - Bix Dev PedcbioPortal Support: Update PPTC study reference [Ticket 375](https://github.com/PediatricOpenTargets/ticket-tracker/issues/375)
```suggestion
```

unrelated- I put this ticket in the wrong repo! :)

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - 3 Kentucky samples (3 normal)
this will now be in PBTA, can you double check the numbers with the latest files in v12 please

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - `UCSC_hg19-GRCh37_Ensembl2RefSeq.tsv`
I think we removed this one
```suggestion
```

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - `fusion_summary_lgg_hgg_foi.tsv`
can you note this one was technically changed in name rather than added?

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - `methyl-md5sum.txt`
Maybe we can call out the methyl data being provided for separate download due to size

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - `fusion_summary_lgat_foi.tsv`
this is the rename I mentioned above

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +      - `tcga-gene-counts-rsem-expected_count-collapsed.rds`
this is removed right now, so should be in another section
```suggestion
      - `tcga-gene-counts-rsem-expected_count-collapsed.rds`
```

2023-04-26 23:14 UTC, jharenza commented on doc/release-notes.md
> +  - Updated data to use GENCODE v39 GDC
Can we create a MAJOR UPDATES section at the top, which summarizes new data added and then also mentions realignment of selected RNA-Seq (PBTA, GKMF, TARGET) to GENCODE v39 and DNA re-annotated with VEP 105 (GENCODE v39 equivalent).

2023-04-28 21:45 UTC, jharenza approved these changes

2023-04-28 21:47 UTC, jharenza requested changes

2023-04-28 21:47 UTC, jharenza commented on doc/release-notes.md
> +        - 315 PBTA WXS samples (160 normal, 155 tumor)
@zzgeng can you update this to current Ns - there is no Kentucky in this release, it is within PBTA, and we might have ~4 more PBTA in addition. thanks

2023-04-29 07:38 UTC, jharenza approved these changes

2023-04-29 18:58 UTC, jharenza commented on doc/release-notes.md
> +    - Create PPTC PDX study base histologies file [Ticket 479](https://github.com/PediatricOpenTargets/ticket-tracker/issues/479)
```suggestion
```

2023-04-29 18:58 UTC, jharenza commented on doc/release-notes.md
> +    - Create chordoma base histologies file [Ticket 484](https://github.com/PediatricOpenTargets/ticket-tracker/issues/484)
```suggestion
```

2023-04-29 18:58 UTC, jharenza commented on doc/release-notes.md
> +      - Re-process DGD panel data [Ticket 429](https://github.com/PediatricOpenTargets/ticket-tracker/issues/429)
```suggestion
```

2023-04-29 18:59 UTC, jharenza commented on doc/release-notes.md
> +    - Creat automated workflow for `histologies-base.tsv` [Ticket 399](https://github.com/PediatricOpenTargets/ticket-tracker/issues/399)
```suggestion
```

2023-04-29 18:59 UTC, jharenza commented on doc/release-notes.md
> +    - Create data warehous dbt tables for OpenTargets histologies mapping files [Ticket 445](https://github.com/PediatricOpenTargets/ticket-tracker/issues/445)
```suggestion
```

2023-04-29 19:00 UTC, jharenza commented on doc/release-notes.md
> +    - Incorrect subtypes [Ticket 489](https://github.com/PediatricOpenTargets/ticket-tracker/issues/489)
```suggestion
```

2023-04-29 19:00 UTC, jharenza commented on doc/release-notes.md
> +    - Update DGD MAF with updated BS IDs for v12 OPC release [Ticket 406](https://github.com/PediatricOpenTargets/ticket-tracker/issues/406)
```suggestion
```

2023-04-29 19:01 UTC, jharenza commented on doc/release-notes.md
> +
```suggestion
```

2023-04-30 14:55 UTC, jharenza commented
merging this one without CI, documentation only!

2023-04-30 14:56 UTC, merged