Refactoring molecular-subtyping-EPN module
PediatricOpenTargets/OpenPBTA-analysis pull request #363
Opened 2023-05-10 19:35 UTC by zzgeng

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Update molecular-subtyping-EPN module to include a script to generate JSON file for sample selection.

#### What was your approach?
Add script to generate json file, which includes exact_path_dx and path_free_text_exact for CRANIO sample subsetting.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/543

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
00-EPN-select-pathology-dx.R
epn-subset/EPN_subtyping_path_dx_strings.json

#### Is there anything that you want to discuss further?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results

#### What types of results are included (e.g., table, figure)?
JSON

#### What is your summary of the results?

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

2023-05-18 21:00 UTC, atlas4213 approved these changes
The code logic looks good and the module compiled successfully.

2023-05-24 01:05 UTC, jharenza commented on analyses/molecular-subtyping-EPN/03-summary.Rmd
> +  filter(pathology_diagnosis %in% path_dx_list$exact_path_dx) %>%
Same comment here as in #362

2023-05-24 01:06 UTC, jharenza commented on analyses/molecular-subtyping-EPN/03-summary.Rmd
> +  filter(pathology_diagnosis %in% path_dx_list$exact_path_dx) %>%
just kidding, you have two path dx here.

2023-05-24 01:11 UTC, jharenza requested changes

2023-05-24 01:11 UTC, jharenza commented on analyses/molecular-subtyping-EPN/epn-subset/EPN_subtyping_path_dx_strings.json
> +    "path_free_text_exact": [
here, I think you can pull out a few terms so you aren't listing exact matches, and condense the code. for example, can you use "ependymoma" and "subependymoma" as a common terms and use grepl instead of exact match when filtering? We have actually been adding free text mainly in cases where we do not have distinct path dx. So theoretically, if all of these are being captured with path dx == EPN, then we don't really need free text. One to check would be the subependymoma one.

2023-05-24 01:11 UTC, jharenza commented on analyses/molecular-subtyping-EPN/epn-subset/EPN_subtyping_path_dx_strings.json
> +        "not reported",
```suggestion
```

definitely do not want this here

2023-05-24 01:11 UTC, jharenza requested changes
I made some suggestions

2023-06-01 15:15 UTC, zzgeng commented on analyses/molecular-subtyping-EPN/epn-subset/EPN_subtyping_path_dx_strings.json
> +    "path_free_text_exact": [
All other scripts (01 and 03) only use path_dx for subsetting. So I deleted free text from JSON file, it should not affect the results.

2023-06-01 20:21 UTC, jharenza approved these changes

2023-06-02 13:37 UTC, ewafula approved these changes

2023-06-05 19:59 UTC, merged