Analysis Update: Add EWS subtyping workflow to README
PediatricOpenTargets/OpenPBTA-analysis pull request #465
Opened 2023-11-13 15:05 UTC by zzgeng

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Add EWS subtyping workflow to README

#### What was your approach?
Add EWS subtyping workflow to README

#### What GitHub issue does your pull request address?

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
EWS subtyping

#### Is there anything that you want to discuss further?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

### Results

#### What types of results are included (e.g., table, figure)?

#### What is your summary of the results?

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2023-11-16 16:51 UTC, AntoniaChroni approved these changes
The EWS classification seems to be coming from identification of `_EWSR1_ fusions` from the RNA seq data. In the figure, it is marked DNA methylation instead.

2023-11-16 16:51 UTC, AntoniaChroni commented on analyses/molecular-subtyping-EWS/README.md
>  `01-run-subtyping-ewings.Rmd` identifies sample_id for RNA-Seq samples with hallmark _EWSR1_ fusions and matches sample_id with WGS sample and adds molecular_subtype as "EWS" (Ewing Sarcoma)
```suggestion
`01-run-subtyping-ewings.Rmd` identifies sample_id for RNA-Seq samples with hallmark _EWSR1_ fusions and matches sample_id with WGS sample and adds molecular_subtype as "EWS" (Ewing Sarcoma).
```

2023-11-17 14:40 UTC, naqvia approved these changes
Code looks good, but the flow diagram should say fusion as that is what defines EWS.

2023-11-25 21:33 UTC, jharenza requested changes
Hi @zzgeng - in the subtyping (maybe this is unclear in the readme) - we are checking path dx == EWS OR methylation classification == EWS, so can you update that here? If the path dx is not EWS, then samples undergo pathology review before we classify as EWS, and that should also be captured.

2023-11-29 18:47 UTC, jharenza approved these changes

2023-11-29 21:59 UTC, jharenza commented
docs only, no need for GA

2023-11-29 21:59 UTC, merged