WXS CNV annotated seg file generation for V7 - part 1
PediatricOpenTargets/OpenPBTA-analysis pull request #58
Opened 2021-07-19 17:22 UTC by runjin326

### Purpose/implementation Section
Modify scripts `rna-expression-validation.R` and `run-prepare-cn-OpenTarget.sh` to use RNA independent samples `independent-specimens.rnaseq.primary.tsv` and combined gene expression file `gene-expression-rsem-tpm-collapsed.rds` as input files.

#### What was your approach?
Modify related scripts 

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/102

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
This PR only handles file name change. Have not ran the script to update the output yet. The output update will be part2 of this PR.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

2021-07-20 21:34 UTC, runjin326 commented
@kgaonkar6, sorry I was wrong before - based on what the code needs, we still need to use DNA independent samples not RNA independent samples. Things to note is that - 
after [filtering on this step](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/7eaf77283dde8a33881f1ada334cdc0c383fb39d/analyses/focal-cn-file-preparation/rna-expression-validation.R#L116-L141), 31 out of 285 sample remain. And after [further filter based on independent samples](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/7eaf77283dde8a33881f1ada334cdc0c383fb39d/analyses/focal-cn-file-preparation/rna-expression-validation.R#L152-L154), only 14 samples are left. 
To my understanding, all the above filtering is trying to find samples in CNV that can unambiguously map back to **one** RNA-seq so that we can match and visualize. So can we do the following instead?

# find the `Kids_First_Participant_ID` for all CNV samples 
`participant_id <- histologies_df %>% filter(Kids_First_Biospecimen_ID %in% CNVsample) %>% pull(Kids_First_Participant_ID)`
# find unambiguous samples which would be ones that only has **one** DNA samples only - so that we can unambiguously match back
```
participant_df <- histologies_df %>% filter(Kids_First_Participant_ID %in% participant_id)
unambiguous_participant <- participant_df  %>% filter(sample_type == "Tumor") %>% filter(experimental_strategy != "RNA-Seq") %>% group_by(Kids_First_Participant_ID) %>% tally() %>% dplyr::filter(n =1) %>% dplyr::pull(Kids_First_Participant_ID)
```
# finally find the matching bio specimen ID for the matched RNA samples 
`rna_matched_samples <- participant_df %>% filter(Kids_First_Participant_ID %in% unambiguous_samples) %>% filter(experimental_strategy == "RNA-Seq") %>% pull(Kids_First_Biospecimen_ID)`
This gives us 147 specimens.

2021-07-23 16:01 UTC, kgaonkar6 requested changes
Thanks @runjin326 ! Let's not update the independent list in this PR we will use the the same logic to use `independent-specimens.wgswxs.primary.tsv` since it is only used in visualization. As you said we can look into this after the v7 release.

I don't see the output `cnvkit_with_status.tsv`  from `01` added in this PR. I find the easiest way to make sure you have all the updates is to run the whole module with each update to code, add and commit the whole module.

2021-07-23 16:01 UTC, kgaonkar6 commented on analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh
> +independent_specimens_file=${data_dir}/independent-specimens.wgswxspanel.primary.tsv
change to `independent-specimens.wgswxspanel.primary.tsv` is not needed since panel samples don't have cnv data produced.

2021-07-23 16:01 UTC, kgaonkar6 commented on analyses/focal-cn-file-preparation/run-prepare-cn.sh
> +independent_specimens_file=${data_dir}/independent-specimens.wgswxspanel.primary.tsv
Update not needed

2021-07-23 16:01 UTC, kgaonkar6 commented on analyses/focal-cn-file-preparation/rna-expression-validation.R
> +#   --independent_specimens_file data/independent-specimens.wgswxspanel.primary.tsv \
Update not needed here

2021-07-23 16:21 UTC, runjin326 commented
@kgaonkar6, I reverted back the changes to independent specimens. For the output `cnvkit_with_status.tsv`, it is put in the scratch folder by this script and it is 119.8MB so I couldn't push it. Any idea how I can add file like that?

2021-07-23 16:48 UTC, kgaonkar6 commented
Oh sorry, `scratch` files are not added to github. I think you can just rerun the whole module in part2 #60 just to make  sure the updates are added in results.

2021-07-23 18:27 UTC, kgaonkar6 approved these changes
Thanks for the update @runjin326 ! LGTM

2021-07-23 18:32 UTC, merged