Previously missing PB subtypes added
PediatricOpenTargets/OpenPBTA-analysis pull request #601
Opened 2024-07-22 17:49 UTC by sangeetashukla

### Purpose/implementation Section
Add PPTID subtypes

#### What scientific question is your analysis addressing?
There were some PPT ID subtypes that were not added to the module earlier. The module needed updates to include those additional subtypes.

#### What was your approach?
Review the input data source to ascertain which subtypes were missed.
Correctly map the pathology_free_text_diagnosis to molecular_subtype_methyl
Followed by mapping molecular_subtype correctly
Run the module to re-generate subtypes in the results/ directory

#### What GitHub issue does your pull request address?
[Issue 590](https://github.com/d3b-center/OpenPedCan-analysis/issues/590)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
Please review the subtypes for their acceptable nomenclature

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results

#### What types of results are included (e.g., table, figure)?

#### What is your summary of the results?

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2024-07-31 20:03 UTC, jharenza commented on analyses/molecular-subtyping-PB/01-molecular-subtype-pineoblastoma.Rmd
> +    dkfz_v12_methylation_subclass == "CTRL_PIN" ~ "CTRL, PIN"
```suggestion
    dkfz_v12_methylation_subclass == "PB_GRP2" ~ "PB, Group 2",
    dkfz_v12_methylation_subclass == "PPTID_A" ~ "PB, PPTID",
```
hi @sangeetashukla I think we only wanted to add this one - can you update ?

2024-07-31 20:04 UTC, jharenza commented on analyses/molecular-subtyping-PB/01-molecular-subtype-pineoblastoma.Rmd
> +## CTRL_PIN: Prostatic Intraepithelial Neoplasia (PIN), Control
```suggestion
## PPTID_A: Ppineal Parenchymal Tumor of Intermediate Differentiation Type A
```

2024-07-31 20:04 UTC, jharenza commented on analyses/molecular-subtyping-PB/01-molecular-subtype-pineoblastoma.Rmd
> +                                       molecular_subtype_methyl == "CTRL, PIN" ~ "CTRL, PIN"))
```suggestion
                                       molecular_subtype_methyl == "PB, Group 2" ~ "PB, Group 2",
                                       molecular_subtype_methyl == "PB, PPTID" ~ "PB, PPTID"))
```

2024-08-02 15:14 UTC, jharenza requested changes
hi @sangeetashukla I left some comments for changes required here

2024-08-06 15:25 UTC, sangeetashukla commented
> hi @sangeetashukla I left some comments for changes required here

Hi @jharenza I have made the changes. Please take a look when you can.

2024-08-15 16:54 UTC, jharenza commented on analyses/molecular-subtyping-PB/01-molecular-subtype-pineoblastoma.Rmd
> +## PPTID_A: Ppineal Parenchymal Tumor of Intermediate Differentiation Type A
```suggestion
## PPTID_A: Pineal Parenchymal Tumor of Intermediate Differentiation Type A
```

2024-08-15 17:07 UTC, jharenza approved these changes
hi @sangeetashukla thanks for the update. I found a bug where the low conf methyl subtypes were being propagated and pushed a commit for that. This looks good now, no new samples subtyped but the code exists now. Let's see if it passes.

2024-08-16 14:16 UTC, merged